#ifndef CUSTOM_BACNET_CONFIG_H
#define CUSTOM_BACNET_CONFIG_H

#undef BACNET_VENDOR_ID
#undef BACNET_VENDOR_NAME

#define BACNET_VENDOR_ID 1129
#define BACNET_VENDOR_NAME "Georg Fischer JRG AG"

#define BACNET_DEVICE_LOCATION "Europe"
#define BACNET_DEVICE_DESCRIPTION "server"
#define BACNET_DEVICE_MODEL "Hycleen Automation Master"

#define BACNET_SEGMENTATION_SUPPORT SEGMENTATION_NONE

#define MAX_DESCRIPTION_LENGTH 64
#define MAX_DEVICE_TYPE_LENGTH 32
#define MAX_OBJECT_NAME_LENGTH 64
#define MAX_CHARACTERSTRING_LENGTH 64
#define MAX_VENDOR_NAME_LENGTH 32
#define MAX_MODEL_NAME_LENGTH 32
#define MAX_VERSION_LENGTH 32
#define MAX_LOCATION_LENGTH 32
#define MAX_STATE_TEXT_LENGTH 32
#define MAX_BIT_TEXT_LENGTH 32

#endif /* CUSTOM_BACNET_CONFIG_H */
